# Disparo manual
name: 'Execução Manual - Trabalho final'

on:
  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      # Clone do projeto
      - uses: actions/checkout@v4

      # Instalação do Node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Instalação do Mocha
      - name: Instalando Mocha
        run: npm install mocha

      # Exe utando os testes
      - name: Executando Testes
        run: npm run test
